# Generated by Django 5.0.2 on 2024-05-06 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ysof_articles',
            fields=[
                ('arid', models.BigAutoField(primary_key=True, serialize=False)),
                ('artitle', models.CharField(max_length=51)),
                ('arcover', models.ImageField(blank=True, null=True, upload_to='articlescover/')),
                ('arcontent', models.TextField()),
                ('arprivate', models.IntegerField(default=1, null=True)),
                ('archeck', models.IntegerField(default=0, null=True)),
                ('arview', models.IntegerField(default=0, null=True)),
                ('arlike', models.IntegerField(default=0, null=True)),
                ('arsave', models.IntegerField(default=0, null=True)),
                ('arshare', models.IntegerField(default=0, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('aruserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
