# Generated by Django 5.0.2 on 2024-08-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ysof_articles',
            name='arcomment',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
