# Generated by Django 5.0.2 on 2024-08-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_ysof_articles_arcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ysof_articles',
            name='arprivate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
