# Generated by Django 5.0.2 on 2024-08-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_alter_ysof_articles_arprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ysof_articles',
            name='artags',
            field=models.TextField(default=''),
        ),
    ]
