# Generated by Django 5.0.2 on 2024-05-06 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ysof_images',
            fields=[
                ('imid', models.BigAutoField(primary_key=True, serialize=False)),
                ('impath', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('imarticleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.ysof_articles')),
            ],
        ),
    ]
