# Generated by Django 4.2.7 on 2023-11-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='context',
            field=models.CharField(max_length=50),
        ),
    ]
