# Generated by Django 4.2.7 on 2023-11-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_comment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ysof_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
