# Generated by Django 5.0.2 on 2024-04-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ysof_users',
            name='usersex',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
